#!/bin/bash

hcp_dir=/project/akhanf/HCP_1200

hcp_uri=s3://hcp-openaccess/HCP

mkdir -p $hcp_dir

list_name=UR100.txt


echo aws s3 cp $hcp_uri/$list_name $hcp_dir/$list_name
aws s3 cp $hcp_uri/$list_name $hcp_dir/$list_name

for subj in `cat $hcp_dir/$list_name`
do
  echo aws s3 cp --recursive $hcp_uri/$subj $hcp_dir/$subj
  aws s3 cp --recursive $hcp_uri/$subj $hcp_dir/$subj
done



